/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Mail (AppleScript)
 #	author : miyako
 #	4/26/18
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"

// --- Mail
void Mail_Get_selection(sLONG_PTR *pResult, PackagePtr pParams);
